# Default initial positions for robot_arm_description's ros2_control fake system

initial_positions:
  joint1: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0
  joint_right: 0.001
  position_base_theta: 0
  position_base_x: 0
  position_base_y: 0