# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    hand_controller:
      type: position_controllers/GripperActionController

    arm_move_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hand_controller:
  ros__parameters:
    joint: joint_right

arm_move_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - position_base_x
      - position_base_y
      - position_base_theta
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity